"use client";
import React, { useEffect, useId, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { useOutsideClick } from "@/hooks/use-outside-click";


const reports = [
  {
    title: "Monthly Performance Report",
    description: "Performance metrics for January 2024.",
    fileUrl: "https://example.com/reports/jan-performance.pdf",
    generatedBy: "John Doe",
    type: "Performance",
  },
  {
    title: "Marketing Analytics",
    description: "Data-driven insights on recent campaigns.",
    fileUrl: "https://example.com/reports/marketing-analytics.pdf",
    generatedBy: "Jane Smith",
    type: "Analytics",
  },
];

export function ExpandableCardDemo() {
  const [active, setActive] = useState(null);
  const ref = useRef(null);
  const id = useId();

  useEffect(() => {
    function onKeyDown(event) {
      if (event.key === "Escape") {
        setActive(null);
      }
    }

    document.body.style.overflow = active ? "hidden" : "auto";
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [active]);

  useOutsideClick(ref, () => setActive(null));

  return (
    <>
      <AnimatePresence>
        {active && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/20 h-full w-full z-10"
          />
        )}
      </AnimatePresence>

      <AnimatePresence>
        {active && (
          <div className="fixed inset-0 flex items-center justify-center z-50 px-4">
            <motion.div
              layoutId={`card-${active.title}-${id}`}
              ref={ref}
              className="w-full max-w-2xl bg-white dark:bg-neutral-900 rounded-lg shadow-lg overflow-hidden"
            >
              {/* Report Header */}
              <div className="p-6 flex justify-between items-center border-b">
                <div>
                  <motion.h3 className="font-bold text-lg text-gray-800 dark:text-white">
                    {active.title}
                  </motion.h3>
                  <p className="text-gray-600 dark:text-gray-400 text-sm">
                    Generated by: {active.generatedBy}
                  </p>
                </div>
                <button
                  onClick={() => setActive(null)}
                  className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300"
                >
                  ✖
                </button>
              </div>

              {/* Report Details */}
              <div className="p-6">
                <p className="text-gray-700 dark:text-gray-300">{active.description}</p>
              </div>

              {/* View Report Button */}
              <div className="p-6 border-t">
                <a
                  href={active.fileUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-full block text-center px-4 py-2 bg-[#0D578C] text-white rounded-lg hover:bg-[#094266]"
                >
                  View Report
                </a>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      <div className="max-w-3xl mx-auto mt-6 space-y-4">
        {reports.map((report) => (
          <motion.div
            key={report.title}
            layoutId={`card-${report.title}-${id}`}
            onClick={() => setActive(report)}
            className="p-6 flex justify-between items-center border rounded-lg shadow-md hover:shadow-lg cursor-pointer transition-all dark:bg-neutral-800 dark:border-neutral-700"
          >
            <div>
              <h3 className="font-semibold text-gray-800 dark:text-white">{report.title}</h3>
              <p className="text-sm text-gray-600 dark:text-gray-400">{report.description}</p>
            </div>
            <button className="px-4 py-2 text-sm font-semibold bg-[#0D578C] text-white rounded-full hover:bg-[#094266]">
              View
            </button>
          </motion.div>
        ))}
      </div>
    </>
  );
}
